Tesst docker compose up for project

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -70,144 +70,155 @@ jobs:
       run: |
         echo "Value of MY_ENV_VAR is $MY_ENV_VAR"
         ls -la
+
+    - name: Start containers microservice-base
+      run: |
         cd python-microservice-base
-        ls -la
+        git checkout -b htv3hc/feat/dockerize-microservice-base origin/htv3hc/feat/dockerize-microservice-base
+        cd MicroserviceBase
+        docker-compose -f "docker-compose.yml" up -d --build
+
+    - name: Start containers
+      run: |
         cd python-microservice-cleware-switch
-        ls -la
+        git checkout -b htv3hc/feat/dockerize-cleware-service origin/htv3hc/feat/dockerize-cleware-service
+        docker-compose -f "docker-compose.yml" up -d --build
 
-    - name: Build
-      run: go build -v ./...
 
-    - name: Test
-      run: |
-        go test -v ./... 2>&1 | tee -a tee console_log.txt
-        mkdir logfile
-        mv console_log.txt ./logfile
-        ls -al
-        ls -la ./logfile
 
-    - name: Check test results
-      run: |
-        if [ $? -eq 0 ]; then
-          echo "Tests passed!"
-        else
-          echo "Tests failed!"
-          exit 1
-        fi
+  #   - name: Build
+  #     run: go build -v ./...
+
+  #   - name: Test
+  #     run: |
+  #       go test -v ./... 2>&1 | tee -a tee console_log.txt
+  #       mkdir logfile
+  #       mv console_log.txt ./logfile
+  #       ls -al
+  #       ls -la ./logfile
+
+  #   - name: Check test results
+  #     run: |
+  #       if [ $? -eq 0 ]; then
+  #         echo "Tests passed!"
+  #       else
+  #         echo "Tests failed!"
+  #         exit 1
+  #       fi
     
-    - name: Test python
-      run: |
-        python hello.py 2>&1 | tee output.txt
+  #   - name: Test python
+  #     run: |
+  #       python hello.py 2>&1 | tee output.txt
         
-        exit_code=${PIPESTATUS[0]}
+  #       exit_code=${PIPESTATUS[0]}
 
-        if [ $exit_code -eq 255 ]; then
-            echo "Script kết thúc với exit code 1."
-            exit 1
-        else
-            echo "Script kết thúc với exit code khác 1."
-        fi
+  #       if [ $exit_code -eq 255 ]; then
+  #           echo "Script kết thúc với exit code 1."
+  #           exit 1
+  #       else
+  #           echo "Script kết thúc với exit code khác 1."
+  #       fi
 
-    - name: Upload logs test
-      if: success() || failure()
-      uses: actions/upload-artifact@v3
-      with:
-        name: log-result
-        path: |
-          ${{ runner.workspace }}/logfile/*
+  #   - name: Upload logs test
+  #     if: success() || failure()
+  #     uses: actions/upload-artifact@v3
+  #     with:
+  #       name: log-result
+  #       path: |
+  #         ${{ runner.workspace }}/logfile/*
 
-  collect-log:
-    name: Collect console log
-    runs-on: ubuntu-latest
-    needs: build  
-    steps:
-    - name: Check out repo's default branch
-      uses: actions/checkout@v3
+  # collect-log:
+  #   name: Collect console log
+  #   runs-on: ubuntu-latest
+  #   needs: build  
+  #   steps:
+  #   - name: Check out repo's default branch
+  #     uses: actions/checkout@v3
 
-    - name: Print Job ID
-      run: |
-        echo "Job ID from job1: $JOB1_JOB_ID"
+  #   - name: Print Job ID
+  #     run: |
+  #       echo "Job ID from job1: $JOB1_JOB_ID"
 
-    - name: Collect log 
-      run: |
-        echo "Current runner id: $CURRENT_RUNNER_ID"
-        gh run view $CURRENT_RUNNER_ID --log > console_log.txt
+  #   - name: Collect log 
+  #     run: |
+  #       echo "Current runner id: $CURRENT_RUNNER_ID"
+  #       gh run view $CURRENT_RUNNER_ID --log > console_log.txt
 
-    - name: Upload built package
-      uses: actions/upload-artifact@v3
-      with:
-        name: upload log artifacts
-        path: console_log.txt
+  #   - name: Upload built package
+  #     uses: actions/upload-artifact@v3
+  #     with:
+  #       name: upload log artifacts
+  #       path: console_log.txt
 
-  display-result:
-    name: Display result
-    runs-on: ubuntu-latest
-    if: github.event_name == 'push'
+  # display-result:
+  #   name: Display result
+  #   runs-on: ubuntu-latest
+  #   if: github.event_name == 'push'
 
-    steps:
-      - name: Check out repo's default branch
-        uses: actions/checkout@v3
+  #   steps:
+  #     - name: Check out repo's default branch
+  #       uses: actions/checkout@v3
   
-      - name: Fetch Pipeline Results
-        run: |
-          # Set up your GitHub Personal Access Token (PAT)
-          GH_TOKEN_SECRET=${{ secrets.GITHUB_TOKEN }}
+  #     - name: Fetch Pipeline Results
+  #       run: |
+  #         # Set up your GitHub Personal Access Token (PAT)
+  #         GH_TOKEN_SECRET=${{ secrets.GITHUB_TOKEN }}
           
-          echo "${{ github.repository }}"
+  #         echo "${{ github.repository }}"
 
-          # Get the GitHub Run ID for the current workflow run
-          RUN_ID=$(curl -s -X GET -H "Authorization: Bearer $GH_TOKEN_SECRET" \
-            "https://api.github.com/repos/${{ github.repository }}/actions/runs" | \
-            jq -r '.workflow_runs[0].id')
+  #         # Get the GitHub Run ID for the current workflow run
+  #         RUN_ID=$(curl -s -X GET -H "Authorization: Bearer $GH_TOKEN_SECRET" \
+  #           "https://api.github.com/repos/${{ github.repository }}/actions/runs" | \
+  #           jq -r '.workflow_runs[0].id')
           
-          echo $RUN_ID
+  #         echo $RUN_ID
   
-          # Fetch the workflow run details
-          PIPELINE=$(curl -s -X GET -H "Authorization: Bearer $GH_TOKEN_SECRET" \
-            "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID")
+  #         # Fetch the workflow run details
+  #         PIPELINE=$(curl -s -X GET -H "Authorization: Bearer $GH_TOKEN_SECRET" \
+  #           "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID")
 
-          echo "###########################################"
-          # Print the pipeline details
-          echo "$PIPELINE"
+  #         echo "###########################################"
+  #         # Print the pipeline details
+  #         echo "$PIPELINE"
 
-      - name: Create comment on PR
-        run: |
-          pipeline_result="PASS"
+  #     - name: Create comment on PR
+  #       run: |
+  #         pipeline_result="PASS"
 
-          GH_TOKEN_SECRET=${{ secrets.GITHUB_TOKEN }}
+  #         GH_TOKEN_SECRET=${{ secrets.GITHUB_TOKEN }}
 
-          # Sử dụng GitHub API để tạo bình luận
-          curl -X POST -H "Authorization: token $GH_TOKEN_SECRET" \
-          -d '{"body": "Kết quả của pipeline A: '"$pipeline_result"'"}' \
-          "https://api.github.com/repos/${{ github.repository }}/issues/pull/9/comments"
+  #         # Sử dụng GitHub API để tạo bình luận
+  #         curl -X POST -H "Authorization: token $GH_TOKEN_SECRET" \
+  #         -d '{"body": "Kết quả của pipeline A: '"$pipeline_result"'"}' \
+  #         "https://api.github.com/repos/${{ github.repository }}/issues/pull/9/comments"
 
 
-      - name: Fetch Pipeline from Another Repository
-        run: |
-          sleep 180
-          # Set up your GitHub Personal Access Token (PAT)
-          GH_TOKEN_SECRET=${{ secrets.GITHUB_TOKEN }}
+  #     - name: Fetch Pipeline from Another Repository
+  #       run: |
+  #         sleep 180
+  #         # Set up your GitHub Personal Access Token (PAT)
+  #         GH_TOKEN_SECRET=${{ secrets.GITHUB_TOKEN }}
       
-          # Define the target repository and branch
-          TARGET_REPO="huavanthong/microservice-golang"
-          BRANCH="master"  # Replace with the branch name you want to fetch the pipeline from
+  #         # Define the target repository and branch
+  #         TARGET_REPO="huavanthong/microservice-golang"
+  #         BRANCH="master"  # Replace with the branch name you want to fetch the pipeline from
       
-          # Get the GitHub Run ID for the workflow run of the target repository
-          RUN_ID=$(curl -s -X GET -H "Authorization: Bearer $GH_TOKEN_SECRET" \
-            "https://api.github.com/repos/$TARGET_REPO/actions/runs" | \
-            jq -r ".workflow_runs[] | select(.head_branch == \"$BRANCH\").id")
+  #         # Get the GitHub Run ID for the workflow run of the target repository
+  #         RUN_ID=$(curl -s -X GET -H "Authorization: Bearer $GH_TOKEN_SECRET" \
+  #           "https://api.github.com/repos/$TARGET_REPO/actions/runs" | \
+  #           jq -r ".workflow_runs[] | select(.head_branch == \"$BRANCH\").id")
 
-          echo "Runner ID is $RUN_ID"
+  #         echo "Runner ID is $RUN_ID"
           
-          echo "Sleep"
-          if [ -n "$RUN_ID" ]; then
-            # Fetch the details of the workflow run
-            PIPELINE=$(curl -s -X GET -H "Authorization: Bearer $GH_TOKEN_SECRET" \
-              "https://api.github.com/repos/$TARGET_REPO/actions/runs/$RUN_ID")
+  #         echo "Sleep"
+  #         if [ -n "$RUN_ID" ]; then
+  #           # Fetch the details of the workflow run
+  #           PIPELINE=$(curl -s -X GET -H "Authorization: Bearer $GH_TOKEN_SECRET" \
+  #             "https://api.github.com/repos/$TARGET_REPO/actions/runs/$RUN_ID")
       
-            # Print the pipeline details
-            echo "$PIPELINE"
-          else
-            echo "No workflow run found for branch $BRANCH in repository $TARGET_REPO."
-          fi
+  #           # Print the pipeline details
+  #           echo "$PIPELINE"
+  #         else
+  #           echo "No workflow run found for branch $BRANCH in repository $TARGET_REPO."
+  #         fi
         
